"""
scrapedatshi._templates._env
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Static template strings for .env, .gitignore, and the scaffold README.
"""

ENV_TEMPLATE = """\
# scrapedatshi API key — get yours at https://scrapedatshi.com/portal/register
SCRAPEDATSHI_API_KEY=sds_...

# ── Embedding providers (fill in whichever you use) ──────────────────────────
OPENAI_API_KEY=sk-...
COHERE_API_KEY=
GEMINI_API_KEY=AIza...
MISTRAL_API_KEY=
VOYAGE_API_KEY=
# OLLAMA_ENDPOINT=https://abc123.ngrok-free.app  # ngrok URL for local Ollama

# ── Vector databases (fill in whichever you use) ─────────────────────────────
PINECONE_API_KEY=pc-...
PINECONE_INDEX_HOST=https://my-index-abc123.svc.pinecone.io

QDRANT_URL=https://your-cluster.qdrant.io
QDRANT_API_KEY=

SUPABASE_CONNECTION_STRING=postgresql://...
SUPABASE_TABLE_NAME=documents

WEAVIATE_URL=https://your-cluster.weaviate.network
WEAVIATE_API_KEY=

MONGODB_CONNECTION_STRING=mongodb+srv://...
MONGODB_DATABASE_NAME=mydb
MONGODB_COLLECTION_NAME=documents

CHROMA_HOST=localhost
CHROMA_PORT=8000
CHROMA_COLLECTION_NAME=documents

LANCEDB_PATH=./lancedb
LANCEDB_TABLE_NAME=documents

# ── LLM providers (for schema extraction + contextual retrieval) ──────────────
ANTHROPIC_API_KEY=sk-ant-...
# OPENAI_API_KEY already set above
# GEMINI_API_KEY already set above
"""

GITIGNORE_TEMPLATE = """\
.env
__pycache__/
*.pyc
*.pyo
.DS_Store
*.auth.json
"""

README_TEMPLATE = """\
# scrapedatshi sandbox

Generated by `scrapedatshi init`. Each script in `examples/` is pre-wired for
one scrapedatshi pipeline method — just fill in your targets and keys, then run.

## Quick start

1. Add your API keys to `.env`
2. Run the discovery script to see all supported providers:

   ```bash
   python examples/00_discover_providers.py
   ```

3. Pick an example and run it:

   ```bash
   python examples/01_scrape_url.py
   ```

## Examples

| File | What it does |
|---|---|
| `00_discover_providers.py` | List all embedding, VDB, and LLM providers + required fields |
| `01_scrape_url.py` | Scrape a URL → clean Markdown |
| `02_pdf_extract.py` | Extract text or tables from a PDF (URL or local file) |
| `03_scrape_file.py` | Parse a local file → clean Markdown |
| `04_chunk_url.py` | Scrape a URL and chunk it into RAG-ready segments |
| `05_chunk_file.py` | Parse a local file and chunk it |
| `06_crawl_site.py` | Crawl an entire site and chunk all pages |
| `07_sync_to_vdb.py` | Scrape URL → embed → inject into vector DB |
| `08_ingest_file.py` | Local file → embed → inject into vector DB |
| `09_ingest_scraped.py` | Bulk-ingest a folder of pre-scraped files |
| `10_autorag.py` | Crawl entire site → embed → inject into vector DB |
| `11_schema_extract.py` | Extract structured JSON from a URL using your LLM |
| `12_extract_crawl.py` | Multi-page schema extraction via site crawl |
| `13_query_vdb.py` | Semantic search against your vector DB |
| `14_rag_chat.py` | Retrieve chunks + generate a grounded LLM answer |
| `15_inspect_vdb.py` | Read vector DB metadata (free — no credits charged) |
| `16_capture_session.py` | Capture a browser session for authenticated scraping |

## Docs

- API reference: https://scrapedatshi.com/dev
- SDK on PyPI: https://pypi.org/project/scrapedatshi/
- GitHub: https://github.com/scrapedatshi/scrapedatshi-py
"""
