"""
scrapedatshi CLI — project scaffolding tool.

Usage:
    scrapedatshi init [project-name]
"""

from __future__ import annotations

import os
import sys
import textwrap

# ── Scaffold file contents ────────────────────────────────────────────────────

_ENV_TEMPLATE = """\
# scrapedatshi API key — get yours at https://scrapedatshi.com/portal/register
SCRAPEDATSHI_API_KEY=sds_...

# ── Embedding providers (fill in whichever you use) ──────────────────────────
OPENAI_API_KEY=sk-...
COHERE_API_KEY=
GEMINI_API_KEY=AIza...
MISTRAL_API_KEY=
VOYAGE_API_KEY=
# OLLAMA_ENDPOINT=https://abc123.ngrok-free.app  # ngrok URL for local Ollama

# ── Vector databases (fill in whichever you use) ─────────────────────────────
PINECONE_API_KEY=pc-...
PINECONE_INDEX_HOST=https://my-index-abc123.svc.pinecone.io

QDRANT_URL=https://your-cluster.qdrant.io
QDRANT_API_KEY=

SUPABASE_CONNECTION_STRING=postgresql://...
SUPABASE_TABLE_NAME=documents

WEAVIATE_URL=https://your-cluster.weaviate.network
WEAVIATE_API_KEY=

MONGODB_CONNECTION_STRING=mongodb+srv://...
MONGODB_DATABASE_NAME=mydb
MONGODB_COLLECTION_NAME=documents

CHROMA_HOST=localhost
CHROMA_PORT=8000
CHROMA_COLLECTION_NAME=documents

LANCEDB_PATH=./lancedb
LANCEDB_TABLE_NAME=documents

# ── LLM providers (for schema extraction + contextual retrieval) ──────────────
ANTHROPIC_API_KEY=sk-ant-...
# OPENAI_API_KEY already set above
# GEMINI_API_KEY already set above
"""

_GITIGNORE_TEMPLATE = """\
.env
__pycache__/
*.pyc
*.pyo
.DS_Store
*.auth.json
"""

_README_TEMPLATE = """\
# scrapedatshi sandbox

Generated by `scrapedatshi init`. Each script in `examples/` is pre-wired for
one scrapedatshi pipeline method — just fill in your targets and keys, then run.

## Quick start

1. Add your API keys to `.env`
2. Run the discovery script to see all supported providers:

   ```bash
   python examples/00_discover_providers.py
   ```

3. Pick an example and run it:

   ```bash
   python examples/01_chunk_url.py
   ```

## Examples

| File | What it does |
|---|---|
| `00_discover_providers.py` | List all embedding, VDB, and LLM providers + required fields |
| `01_chunk_url.py` | Scrape a URL and chunk it into RAG-ready segments |
| `02_chunk_file.py` | Parse a local file and chunk it |
| `03_crawl_site.py` | Crawl an entire site and chunk all pages |
| `04_sync_to_vdb.py` | Scrape URL → embed → inject into vector DB |
| `05_ingest_file.py` | Local file → embed → inject into vector DB |
| `06_ingest_scraped.py` | Bulk-ingest a folder of pre-scraped files |
| `07_autorag.py` | Crawl entire site → embed → inject into vector DB |
| `08_schema_extract.py` | Extract structured JSON from a URL using your LLM |
| `09_extract_crawl.py` | Multi-page schema extraction via site crawl |
| `10_query_vdb.py` | Semantic search against your vector DB |
| `11_rag_chat.py` | Retrieve chunks + generate a grounded LLM answer |
| `12_inspect_vdb.py` | Read vector DB metadata (free — no credits charged) |
| `13_capture_session.py` | Capture a browser session for authenticated scraping |

## Docs

- API reference: https://scrapedatshi.com/dev
- SDK on PyPI: https://pypi.org/project/scrapedatshi/
- GitHub: https://github.com/scrapedatshi/scrapedatshi-py
"""

_EXAMPLES: dict[str, str] = {}

_EXAMPLES["00_discover_providers.py"] = '''\
"""
00_discover_providers.py — List all supported providers and required config fields.

Run this first to see what embedding models, vector databases, and LLM providers
are available, and which environment variables / config fields each one needs.

No API keys required to run this script.
"""

from scrapedatshi.providers import EMBEDDING_PROVIDERS, VECTOR_DB_PROVIDERS, LLM_PROVIDERS

# ── Embedding providers ───────────────────────────────────────────────────────
print("=" * 60)
print("EMBEDDING PROVIDERS")
print("=" * 60)
for key, info in EMBEDDING_PROVIDERS.items():
    req = "API key required" if info.get("requires_api_key") else "No API key"
    print(f"  {key:12s}  {info[\'label\']}")
    print(f"             {req}")
    if info.get("notes"):
        print(f"             {info[\'notes\']}")
    print()

# ── Vector database providers ─────────────────────────────────────────────────
print("=" * 60)
print("VECTOR DATABASE PROVIDERS")
print("=" * 60)
for key, info in VECTOR_DB_PROVIDERS.items():
    required = ", ".join(info.get("required_fields", []))
    optional = ", ".join(info.get("optional_fields", []))
    print(f"  {key:20s}  {info[\'label\']}")
    print(f"                       Required fields: {required}")
    if optional:
        print(f"                       Optional fields: {optional}")
    print()

# ── LLM providers ─────────────────────────────────────────────────────────────
print("=" * 60)
print("LLM PROVIDERS  (for schema extraction + contextual retrieval)")
print("=" * 60)
for key, info in LLM_PROVIDERS.items():
    print(f"  {key:12s}  {info[\'label\']}")
    if info.get("notes"):
        print(f"             {info[\'notes\']}")
    print()

print("=" * 60)
print("ENV VARS TO SET IN .env")
print("=" * 60)
print("""
  SCRAPEDATSHI_API_KEY   — your scrapedatshi API key (required for all calls)

  Embedding:
    OPENAI_API_KEY       — OpenAI embeddings + LLM
    COHERE_API_KEY       — Cohere embeddings
    GEMINI_API_KEY       — Google Gemini embeddings + LLM
    MISTRAL_API_KEY      — Mistral embeddings
    VOYAGE_API_KEY       — Voyage AI embeddings
    ANTHROPIC_API_KEY    — Anthropic LLM (Claude)

  Vector DB:
    PINECONE_API_KEY + PINECONE_INDEX_HOST
    QDRANT_URL + QDRANT_API_KEY
    SUPABASE_CONNECTION_STRING + SUPABASE_TABLE_NAME
    WEAVIATE_URL + WEAVIATE_API_KEY
    MONGODB_CONNECTION_STRING + MONGODB_DATABASE_NAME + MONGODB_COLLECTION_NAME
    CHROMA_HOST + CHROMA_PORT + CHROMA_COLLECTION_NAME  (local)
    LANCEDB_PATH + LANCEDB_TABLE_NAME                   (local)
""")
'''

_EXAMPLES["01_chunk_url.py"] = '''\
"""
01_chunk_url.py — Scrape a URL and chunk it into RAG-ready segments.

No vector DB or embedding key required — just your scrapedatshi API key.
"""

import os
from dotenv import load_dotenv
from scrapedatshi import ScrapedatshiClient

load_dotenv()

# ── CONFIGURE ────────────────────────────────────────────────────────────────
URL = "https://docs.example.com"   # ← EDIT: the URL to scrape

# Optional settings (uncomment to use)
# SELECTOR = "article"             # CSS selector to target main content
# CHUNK_SIZE = 512                 # tokens per chunk (default: 400)
# OVERLAP = 50                     # token overlap between chunks (default: 40)
# JS_RENDER = False                # set True for JavaScript-heavy SPAs (billed at $0.0050/URL)

# Authenticated scraping — cookies stay on your machine, never sent to our servers
# COOKIES = {"session": "abc123", "csrf": "xyz"}
# HEADERS = {"Authorization": "Bearer eyJ..."}
# ALLOW_SUBDOMAINS = False         # set True to share cookies with subdomains

# Contextual Retrieval (RAG 2.0) — boosts retrieval accuracy 35–50% ($0.0010/chunk)
# CONTEXTUAL_RETRIEVAL = True
# LLM_PROVIDER = "openai"         # "openai", "anthropic", or "gemini"
# LLM_API_KEY  = os.getenv("OPENAI_API_KEY")
# LLM_MODEL    = "gpt-4o-mini"
# ─────────────────────────────────────────────────────────────────────────────

client = ScrapedatshiClient()  # reads SCRAPEDATSHI_API_KEY from .env

result = client.pipeline.chunk_url(URL)

print(f"URL:          {result.source}")
print(f"Chunks:       {result.total_chunks}")
print(f"Credits used: ${result.credits_used:.4f}")
print(f"Remaining:    ${result.credits_remaining:.4f}")
print()

for i, chunk in enumerate(result.chunks, 1):
    print(f"── Chunk {i} ({chunk.token_estimate} tokens) ──")
    print(chunk.content[:300])
    print()
'''

_EXAMPLES["02_chunk_file.py"] = '''\
"""
02_chunk_file.py — Parse a local file and chunk it into RAG-ready segments.

Supports: .pdf, .md, .txt, .yaml, .yml, .json, .csv, .xlsx, .xls, .docx,
          .ipynb, .html, .htm, .xml, .toml, .ini, .cfg,
          .py, .js, .ts, .jsx, .tsx, .sql, .go, .rb, .java, .cs, .cpp,
          .c, .rs, .php, .sh, .bash, .zsh, .r, .swift, .kt, .scala
No vector DB or embedding key required.

Fetch mode note:
  local (default) — file parsed on your machine, text sent to server for chunking
  server          — file sent to our server for parsing + OCR (use for scanned PDFs)

Optional extras for Excel/Word parsing:
  pip install scrapedatshi[excel]       # for .xlsx/.xls
  pip install scrapedatshi[docx]        # for .docx
  pip install scrapedatshi[all-parsers] # for both
"""

import os
from dotenv import load_dotenv
from scrapedatshi import ScrapedatshiClient

load_dotenv()

# ── CONFIGURE ────────────────────────────────────────────────────────────────
FILE_PATH = "./docs/manual.pdf"    # ← EDIT: path to your local file

# Optional settings (uncomment to use)
# CHUNK_SIZE = 512
# OVERLAP = 50

# Contextual Retrieval (RAG 2.0) — boosts retrieval accuracy 35–50% ($0.0010/chunk)
# CONTEXTUAL_RETRIEVAL = True
# LLM_PROVIDER = "openai"         # "openai", "anthropic", or "gemini"
# LLM_API_KEY  = os.getenv("OPENAI_API_KEY")
# LLM_MODEL    = "gpt-4o-mini"

# For scanned/image-only PDFs that need OCR — switch to server fetch
# client = ScrapedatshiClient(fetch_mode="server")
# ─────────────────────────────────────────────────────────────────────────────

client = ScrapedatshiClient()

result = client.pipeline.chunk_file(FILE_PATH)

print(f"File:         {result.source}")
print(f"Chunks:       {result.total_chunks}")
print(f"Credits used: ${result.credits_used:.4f}")
print(f"Remaining:    ${result.credits_remaining:.4f}")
print()

for i, chunk in enumerate(result.chunks, 1):
    print(f"── Chunk {i} ({chunk.token_estimate} tokens) ──")
    print(chunk.content[:300])
    print()
'''

_EXAMPLES["03_crawl_site.py"] = '''\
"""
03_crawl_site.py — Crawl an entire site and chunk all pages.

Two modes:
  sitemap (default) — reads sitemap.xml, best for docs/blogs
  spider            — follows links, works on any site

No vector DB or embedding key required.

Dependencies:
  pip install python-dotenv
"""

import os
from dotenv import load_dotenv
from scrapedatshi import ScrapedatshiClient

load_dotenv()

# ── CONFIGURE ────────────────────────────────────────────────────────────────
URL        = "https://docs.example.com"   # ← EDIT: root URL to crawl
MAX_PAGES  = 10                           # ← EDIT: max pages to crawl
CRAWL_MODE = "sitemap"                    # "sitemap" or "spider"

# Optional filters (uncomment to use)
# INCLUDE_PATTERN = "/docs/"             # only crawl URLs containing this
# EXCLUDE_PATTERN = "/blog/"             # skip URLs containing this
# CHUNK_SIZE = 512
# OVERLAP = 50
# JS_RENDER = False                      # set True to use a headless browser — can help with
#                                        # JavaScript-heavy pages and certain access restrictions
#                                        # ($0.0050/URL surcharge)

# Authenticated crawl — cookies stay on your machine, never sent to our servers
# COOKIES = {"session": "abc123"}
# HEADERS = {"Authorization": "Bearer eyJ..."}
# ALLOW_SUBDOMAINS = False               # set True to crawl subdomains (e.g. wiki.company.com)

# Contextual Retrieval (RAG 2.0) — boosts retrieval accuracy 35–50% ($0.0010/chunk)
# CONTEXTUAL_RETRIEVAL = True
# LLM_PROVIDER = "openai"               # "openai", "anthropic", or "gemini"
# LLM_API_KEY  = os.getenv("OPENAI_API_KEY")
# LLM_MODEL    = "gpt-4o-mini"
# ─────────────────────────────────────────────────────────────────────────────

client = ScrapedatshiClient()

result = client.pipeline.crawl(
    URL,
    max_pages=MAX_PAGES,
    crawl_mode=CRAWL_MODE,
    # js_render=JS_RENDER,
    # include_pattern=INCLUDE_PATTERN,
    # exclude_pattern=EXCLUDE_PATTERN,
    # cookies=COOKIES,
    # headers=HEADERS,
    # allow_subdomains=ALLOW_SUBDOMAINS,
)

print(f"URL:          {result.source_url}")
print(f"Pages:        {result.pages_crawled}")
print(f"Chunks:       {result.total_chunks}")
print(f"Credits used: ${result.credits_used:.4f}")
print(f"Remaining:    ${result.credits_remaining:.4f}")
print()

for i, chunk in enumerate(result.chunks[:5], 1):
    print(f"── Chunk {i} ──")
    print(chunk.content[:200])
    print()
'''

_EXAMPLES["04_sync_to_vdb.py"] = '''\
"""
04_sync_to_vdb.py — Scrape a URL → embed → inject into your vector database.

Full pipeline in one call. Requires embedding + vector DB keys.
"""

import os
from dotenv import load_dotenv
from scrapedatshi import ScrapedatshiClient

load_dotenv()

# ── CONFIGURE ────────────────────────────────────────────────────────────────
URL = "https://docs.example.com"           # ← EDIT: URL to scrape and sync

EMBEDDING_PROVIDER = "openai"              # ← EDIT: embedding provider key
EMBEDDING_MODEL    = "text-embedding-3-small"  # ← EDIT: model name
EMBEDDING_API_KEY  = os.getenv("OPENAI_API_KEY")

VECTOR_DB = "pinecone"                     # ← EDIT: vector DB key
VECTOR_DB_CONFIG = {                       # ← EDIT: your vector DB config
    "api_key":    os.getenv("PINECONE_API_KEY"),
    "index_host": os.getenv("PINECONE_INDEX_HOST"),
}

# Optional settings (uncomment to use)
# SELECTOR = "article"                     # CSS selector to target main content
# CHUNK_SIZE = 512
# OVERLAP = 50
# JS_RENDER = False                        # set True for JavaScript-heavy SPAs ($0.0050/URL)

# Authenticated scraping — cookies stay on your machine, never sent to our servers
# COOKIES = {"session": "abc123"}
# HEADERS = {"Authorization": "Bearer eyJ..."}

# Contextual Retrieval (RAG 2.0) — boosts retrieval accuracy 35–50% ($0.0010/chunk)
# CONTEXTUAL_RETRIEVAL = True
# LLM_PROVIDER = "openai"                 # "openai", "anthropic", or "gemini"
# LLM_API_KEY  = os.getenv("OPENAI_API_KEY")
# LLM_MODEL    = "gpt-4o-mini"
# ─────────────────────────────────────────────────────────────────────────────

client = ScrapedatshiClient()

result = client.pipeline.sync(
    url=URL,
    embedding_provider=EMBEDDING_PROVIDER,
    embedding_api_key=EMBEDDING_API_KEY,
    embedding_model=EMBEDDING_MODEL,
    vector_db=VECTOR_DB,
    vector_db_config=VECTOR_DB_CONFIG,
)

print(f"Status:          {result.status}")
print(f"Chunks created:  {result.chunks_created}")
print(f"Vectors upserted:{result.vectors_upserted}")
print(f"Embedding:       {result.embedding_provider}")
print(f"Vector DB:       {result.vector_db_provider}")
print(f"Credits used:    ${result.credits_used:.4f}")
print(f"Remaining:       ${result.credits_remaining:.4f}")
'''

_EXAMPLES["05_ingest_file.py"] = '''\
"""
05_ingest_file.py — Parse a local file → embed → inject into your vector database.

Supports: .pdf, .md, .txt, .yaml, .yml, .json, .csv, .xlsx, .xls, .docx,
          .ipynb, .html, .htm, .xml, .toml, .ini, .cfg,
          .py (AST-aware: split by class/function),
          .sql (statement-aware: split by CREATE/INSERT/SELECT blocks),
          .js, .ts, .jsx, .tsx, .go, .rb, .java, .cs, .cpp, .c, .rs, .php,
          .sh, .bash, .zsh, .r, .swift, .kt, .scala
Requires embedding + vector DB keys.
"""

import os
from dotenv import load_dotenv
from scrapedatshi import ScrapedatshiClient

load_dotenv()

# ── CONFIGURE ────────────────────────────────────────────────────────────────
FILE_PATH = "./docs/manual.pdf"            # ← EDIT: path to your local file

EMBEDDING_PROVIDER = "openai"
EMBEDDING_MODEL    = "text-embedding-3-small"
EMBEDDING_API_KEY  = os.getenv("OPENAI_API_KEY")

VECTOR_DB = "pinecone"
VECTOR_DB_CONFIG = {
    "api_key":    os.getenv("PINECONE_API_KEY"),
    "index_host": os.getenv("PINECONE_INDEX_HOST"),
}

# Optional settings (uncomment to use)
# CHUNK_SIZE = 512
# OVERLAP = 50

# Contextual Retrieval (RAG 2.0) — boosts retrieval accuracy 35–50% ($0.0010/chunk)
# CONTEXTUAL_RETRIEVAL = True
# LLM_PROVIDER = "openai"                 # "openai", "anthropic", or "gemini"
# LLM_API_KEY  = os.getenv("OPENAI_API_KEY")
# LLM_MODEL    = "gpt-4o-mini"

# For scanned/image-only PDFs that need OCR — switch to server fetch
# client = ScrapedatshiClient(fetch_mode="server")
# ─────────────────────────────────────────────────────────────────────────────

client = ScrapedatshiClient()

result = client.pipeline.ingest(
    file_path=FILE_PATH,
    embedding_provider=EMBEDDING_PROVIDER,
    embedding_api_key=EMBEDDING_API_KEY,
    embedding_model=EMBEDDING_MODEL,
    vector_db=VECTOR_DB,
    vector_db_config=VECTOR_DB_CONFIG,
)

print(f"Status:          {result.status}")
print(f"Chunks created:  {result.chunks_created}")
print(f"Vectors upserted:{result.vectors_upserted}")
print(f"Credits used:    ${result.credits_used:.4f}")
print(f"Remaining:       ${result.credits_remaining:.4f}")
'''

_EXAMPLES["06_ingest_scraped.py"] = '''\
"""
06_ingest_scraped.py — Bulk-ingest a folder of pre-scraped files into your vector DB.

Designed for output from web scrapers (Scrapy, Playwright, Apify, custom scripts).
Each file is parsed locally, chunked, embedded, and injected individually.

Supports: .md, .txt, .json, .yaml, .yml, .csv, .xlsx, .xls, .docx,
          .ipynb, .html, .htm, .xml, .toml, .ini, .cfg,
          .py (AST-aware: split by class/function),
          .sql (statement-aware: split by CREATE/INSERT/SELECT blocks),
          .js, .ts, .jsx, .tsx, .go, .rb, .java, .cs, .cpp, .c, .rs, .php,
          .sh, .bash, .zsh, .r, .swift, .kt, .scala

JSON arrays are automatically detected and each item ingested individually
(Scrapy/crawler output format).
"""

import os
from dotenv import load_dotenv
from scrapedatshi import ScrapedatshiClient

load_dotenv()

# ── CONFIGURE ────────────────────────────────────────────────────────────────
FOLDER_PATH = "./scraped_output/"          # ← EDIT: folder containing your files

# Optional: restrict to specific file types (default: all supported types)
# FILE_EXTENSIONS = [".json"]

# Optional: delay between files in seconds (helps avoid rate limits on large folders)
# BATCH_DELAY = 0.5

EMBEDDING_PROVIDER = "openai"
EMBEDDING_MODEL    = "text-embedding-3-small"
EMBEDDING_API_KEY  = os.getenv("OPENAI_API_KEY")

VECTOR_DB = "pinecone"
VECTOR_DB_CONFIG = {
    "api_key":    os.getenv("PINECONE_API_KEY"),
    "index_host": os.getenv("PINECONE_INDEX_HOST"),
}
# ─────────────────────────────────────────────────────────────────────────────

client = ScrapedatshiClient()

result = client.pipeline.ingest_scraped(
    folder_path=FOLDER_PATH,
    embedding_provider=EMBEDDING_PROVIDER,
    embedding_api_key=EMBEDDING_API_KEY,
    embedding_model=EMBEDDING_MODEL,
    vector_db=VECTOR_DB,
    vector_db_config=VECTOR_DB_CONFIG,
)

print(f"Files processed: {result.files_processed}")
print(f"Files failed:    {result.files_failed}")
print(f"Total chunks:    {result.total_chunks}")
print(f"Vectors upserted:{result.vectors_upserted}")
print(f"Credits used:    ${result.credits_used:.4f}")
print(f"Remaining:       ${result.credits_remaining:.4f}")

if result.errors:
    print()
    print("Errors:")
    for err in result.errors:
        print(f"  ✗ {err[\'file\']} — {err[\'error\']}")
'''

_EXAMPLES["07_autorag.py"] = '''\
"""
07_autorag.py — Crawl an entire site → embed → inject into your vector database.

Full AutoRAG pipeline in one call. Large sites (>200 pages) are auto-batched.
Requires embedding + vector DB keys.
"""

import os
from dotenv import load_dotenv
from scrapedatshi import ScrapedatshiClient

load_dotenv()

# ── CONFIGURE ────────────────────────────────────────────────────────────────
URL        = "https://docs.example.com"   # ← EDIT: root URL to crawl
MAX_PAGES  = 50                           # ← EDIT: max pages to crawl
CRAWL_MODE = "sitemap"                    # "sitemap" or "spider"

# Optional filters (uncomment to use)
# INCLUDE_PATTERN = "/docs/"
# EXCLUDE_PATTERN = "/blog/"
# CHUNK_SIZE = 512
# OVERLAP = 50
# JS_RENDER = False                      # set True to use a headless browser — can help with
#                                        # JavaScript-heavy pages and certain access restrictions
#                                        # ($0.0050/URL surcharge)

# Authenticated crawl — cookies stay on your machine, never sent to our servers
# COOKIES = {"session": "abc123"}
# HEADERS = {"Authorization": "Bearer eyJ..."}
# ALLOW_SUBDOMAINS = False               # set True to crawl subdomains

# Contextual Retrieval (RAG 2.0) — boosts retrieval accuracy 35–50% ($0.0010/chunk)
# CONTEXTUAL_RETRIEVAL = True
# LLM_PROVIDER = "openai"               # "openai", "anthropic", or "gemini"
# LLM_API_KEY  = os.getenv("OPENAI_API_KEY")
# LLM_MODEL    = "gpt-4o-mini"

EMBEDDING_PROVIDER = "openai"
EMBEDDING_MODEL    = "text-embedding-3-small"
EMBEDDING_API_KEY  = os.getenv("OPENAI_API_KEY")

VECTOR_DB = "pinecone"
VECTOR_DB_CONFIG = {
    "api_key":    os.getenv("PINECONE_API_KEY"),
    "index_host": os.getenv("PINECONE_INDEX_HOST"),
}
# ─────────────────────────────────────────────────────────────────────────────

client = ScrapedatshiClient()

result = client.pipeline.autorag(
    url=URL,
    max_pages=MAX_PAGES,
    crawl_mode=CRAWL_MODE,
    embedding_provider=EMBEDDING_PROVIDER,
    embedding_api_key=EMBEDDING_API_KEY,
    embedding_model=EMBEDDING_MODEL,
    vector_db=VECTOR_DB,
    vector_db_config=VECTOR_DB_CONFIG,
)

print(f"Pages crawled:   {result.pages_crawled}")
print(f"Vectors upserted:{result.vectors_upserted}")
print(f"Credits used:    ${result.credits_used:.4f}")
print(f"Remaining:       ${result.credits_remaining:.4f}")

if getattr(result, "auto_batched", False):
    print(f"Auto-batched:    {result.batches_processed} batches")
'''

_EXAMPLES["08_schema_extract.py"] = '''\
"""
08_schema_extract.py — Extract structured JSON from a URL using your LLM.

Define a schema and the API returns a typed JSON object.
Requires an LLM API key (OpenAI, Anthropic, or Gemini).
"""

import os
from dotenv import load_dotenv
from scrapedatshi import ScrapedatshiClient

load_dotenv()

# ── CONFIGURE ────────────────────────────────────────────────────────────────
URL = "https://example.com/products/widget-pro"  # ← EDIT: URL to extract from

SCHEMA = {                                        # ← EDIT: your extraction schema
    "title":       "string — the product name",
    "price":       "number — the price in USD",
    "in_stock":    "boolean — whether the item is in stock",
    "description": "string — the product description",
}

LLM_PROVIDER = "openai"                           # ← EDIT: "openai", "anthropic", or "gemini"
LLM_MODEL    = "gpt-4o-mini"                      # ← EDIT: model name
LLM_API_KEY  = os.getenv("OPENAI_API_KEY")

# Set to True to extract a list of items (e.g. product listing pages)
EXTRACT_AS_LIST = False

# Optional settings (uncomment to use)
# SELECTOR = "article"                             # CSS selector to target main content
# JS_RENDER = False                                # set True for JavaScript-heavy SPAs

# Authenticated scraping — cookies stay on your machine, never sent to our servers
# COOKIES = {"session": "abc123"}
# HEADERS = {"Authorization": "Bearer eyJ..."}
# ─────────────────────────────────────────────────────────────────────────────

client = ScrapedatshiClient()

result = client.pipeline.extract(
    url=URL,
    schema=SCHEMA,
    llm_provider=LLM_PROVIDER,
    llm_api_key=LLM_API_KEY,
    llm_model=LLM_MODEL,
    extract_as_list=EXTRACT_AS_LIST,
)

print(f"URL:          {result.url}")
print(f"Fields:       {result.field_count}")
print(f"Credits used: ${result.credits_used:.4f}")
print(f"Remaining:    ${result.credits_remaining:.4f}")
print()
print("Extracted data:")
import json
print(json.dumps(result.extracted, indent=2))
'''

_EXAMPLES["09_extract_crawl.py"] = '''\
"""
09_extract_crawl.py — Crawl an entire site and extract structured data from every page.

Each page is processed independently — failed pages don\'t abort the batch.
Only successfully extracted pages are billed.
"""

import os
from dotenv import load_dotenv
from scrapedatshi import ScrapedatshiClient

load_dotenv()

# ── CONFIGURE ────────────────────────────────────────────────────────────────
URL        = "https://example.com/products"  # ← EDIT: root URL to crawl
MAX_PAGES  = 10                              # ← EDIT: max pages to crawl
CRAWL_MODE = "sitemap"                       # "sitemap" or "spider"

SCHEMA = {                                   # ← EDIT: your extraction schema
    "title":    "string — the product name",
    "price":    "number — the price in USD",
    "in_stock": "boolean — whether the item is in stock",
}

LLM_PROVIDER = "openai"
LLM_MODEL    = "gpt-4o-mini"
LLM_API_KEY  = os.getenv("OPENAI_API_KEY")

# Optional filters (uncomment to use)
# INCLUDE_PATTERN = "/products/"             # only crawl URLs containing this
# EXCLUDE_PATTERN = "/archive/"             # skip URLs containing this
# JS_RENDER = False                          # set True for JavaScript-heavy SPAs

# Authenticated crawl — cookies stay on your machine, never sent to our servers
# COOKIES = {"session": "abc123"}
# HEADERS = {"Authorization": "Bearer eyJ..."}
# ALLOW_SUBDOMAINS = False                   # set True to crawl subdomains
# ─────────────────────────────────────────────────────────────────────────────

client = ScrapedatshiClient()

result = client.pipeline.extract_crawl(
    url=URL,
    schema=SCHEMA,
    llm_provider=LLM_PROVIDER,
    llm_api_key=LLM_API_KEY,
    llm_model=LLM_MODEL,
    max_pages=MAX_PAGES,
    crawl_mode=CRAWL_MODE,
)

print(f"Extracted: {result.pages_extracted}/{result.pages_attempted} pages")
print(f"Failed:    {result.pages_failed} pages (not billed)")
print(f"Credits used: ${result.credits_used:.4f}")
print(f"Remaining:    ${result.credits_remaining:.4f}")
print()

for page in result.results:
    if page.ok:
        print(f"  ✓ {page.url}")
        print(f"    {page.extracted}")
    else:
        print(f"  ✗ {page.url} — {page.error}")
'''

_EXAMPLES["10_query_vdb.py"] = '''\
"""
10_query_vdb.py — Semantic search against your vector database.

Embeds a natural language query and retrieves the most relevant chunks.
Run 12_inspect_vdb.py first to confirm the correct embedding model.
"""

import os
from dotenv import load_dotenv
from scrapedatshi import ScrapedatshiClient

load_dotenv()

# ── CONFIGURE ────────────────────────────────────────────────────────────────
QUERY  = "How do I authenticate with the API?"  # ← EDIT: your search query
TOP_K  = 5                                       # number of results to return

EMBEDDING_PROVIDER = "openai"
EMBEDDING_MODEL    = "text-embedding-3-small"    # ← must match ingestion model
EMBEDDING_API_KEY  = os.getenv("OPENAI_API_KEY")

VECTOR_DB = "pinecone"
VECTOR_DB_CONFIG = {
    "api_key":    os.getenv("PINECONE_API_KEY"),
    "index_host": os.getenv("PINECONE_INDEX_HOST"),
}
# ─────────────────────────────────────────────────────────────────────────────

client = ScrapedatshiClient()

result = client.pipeline.query_vectordb(
    query=QUERY,
    embedding_provider=EMBEDDING_PROVIDER,
    embedding_api_key=EMBEDDING_API_KEY,
    embedding_model=EMBEDDING_MODEL,
    vector_db=VECTOR_DB,
    vector_db_config=VECTOR_DB_CONFIG,
    top_k=TOP_K,
)

print(f"Query:        {QUERY}")
print(f"Results:      {result.chunks_retrieved}")
print(f"Credits used: ${result.credits_used:.4f}")
print(f"Remaining:    ${result.credits_remaining:.4f}")
print()

for i, r in enumerate(result.results, 1):
    print(f"── Result {i}  [score: {r.score:.4f}] ──")
    print(r.text[:400])
    print()
'''

_EXAMPLES["11_rag_chat.py"] = '''\
"""
11_rag_chat.py — Retrieve relevant chunks and generate a grounded LLM answer.

Combines vector search with LLM generation. You bring your own LLM key —
scrapedatshi only charges for the vector retrieval ($0.0002 / chunk).
"""

import os
from dotenv import load_dotenv
from scrapedatshi import ScrapedatshiClient

load_dotenv()

# ── CONFIGURE ────────────────────────────────────────────────────────────────
QUERY  = "How do I authenticate with the API?"  # ← EDIT: your question
TOP_K  = 5

EMBEDDING_PROVIDER = "openai"
EMBEDDING_MODEL    = "text-embedding-3-small"    # ← must match ingestion model
EMBEDDING_API_KEY  = os.getenv("OPENAI_API_KEY")

VECTOR_DB = "pinecone"
VECTOR_DB_CONFIG = {
    "api_key":    os.getenv("PINECONE_API_KEY"),
    "index_host": os.getenv("PINECONE_INDEX_HOST"),
}

LLM_PROVIDER = "openai"                          # ← EDIT: "openai", "anthropic", or "gemini"
LLM_MODEL    = "gpt-4o-mini"
LLM_API_KEY  = os.getenv("OPENAI_API_KEY")
# ─────────────────────────────────────────────────────────────────────────────

client = ScrapedatshiClient()

result = client.pipeline.rag_chat(
    query=QUERY,
    embedding_provider=EMBEDDING_PROVIDER,
    embedding_api_key=EMBEDDING_API_KEY,
    embedding_model=EMBEDDING_MODEL,
    vector_db=VECTOR_DB,
    vector_db_config=VECTOR_DB_CONFIG,
    llm_provider=LLM_PROVIDER,
    llm_api_key=LLM_API_KEY,
    llm_model=LLM_MODEL,
    top_k=TOP_K,
)

print(f"Question: {QUERY}")
print()
print("Answer:")
print(result.answer)
print()
print(f"Based on {result.chunks_retrieved} chunks  |  Credits used: ${result.credits_used:.4f}")
print()
print("Sources:")
for i, source in enumerate(result.sources, 1):
    print(f"  [{i}] score={source.score:.4f}  {source.text[:120]}...")
'''

_EXAMPLES["13_capture_session.py"] = '''\
"""
13_capture_session.py — Capture a browser session for authenticated scraping.

Opens a real, headed browser window so you can log in manually through any
authentication flow (Okta, Duo, standard login forms, MFA, etc.).  Once you
press Enter in the terminal the SDK captures the full browser storage state
(cookies + localStorage) and saves it to session.auth.json.

You can then pass the saved state to any pipeline method via storage_state=.

Requirements:
  pip install scrapedatshi[auth]
  playwright install chromium

How it works:
  1. capture_session() runs on YOUR machine using YOUR IP address.
     This is important — corporate SSO systems trust your IP.
  2. You log in manually in the real browser window.
  3. The captured session state is passed to crawl()/scrape() which
     runs on scrapedatshi\'s cloud infrastructure.
  4. The target site accepts the session because the auth tokens are
     valid — session tokens are IP-independent.

⚠  WARNING: The generated session.auth.json contains live security keys
   capable of impersonating your user profile.  Never commit your .auth.json
   files to Git repositories.  This project\'s .gitignore already filters
   *.auth.json automatically.
"""

import json
import os
from dotenv import load_dotenv
from scrapedatshi import ScrapedatshiClient
from scrapedatshi.auth import capture_session

load_dotenv()

# ── CONFIGURE ────────────────────────────────────────────────────────────────
LOGIN_URL   = "https://internal.company.com/login"  # ← EDIT: your login page
CRAWL_URL   = "https://internal.company.com"        # ← EDIT: root URL to crawl
MAX_PAGES   = 20                                     # ← EDIT: max pages to crawl
SESSION_FILE = "session.auth.json"                   # saved session (gitignored)

# Optional: choose browser engine — "chromium" (default), "firefox", or "webkit"
# BROWSER = "chromium"
# ─────────────────────────────────────────────────────────────────────────────

# ── Step 1: Capture session (or load a previously saved one) ─────────────────
if os.path.exists(SESSION_FILE):
    print(f"Loading saved session from {SESSION_FILE}")
    with open(SESSION_FILE) as f:
        state = json.load(f)
else:
    # Opens a real browser window — log in, then press Enter
    state = capture_session(
        url=LOGIN_URL,
        save_to=SESSION_FILE,   # saves to session.auth.json (gitignored)
    )

# ── Step 2: Crawl with the captured session ───────────────────────────────────
client = ScrapedatshiClient()

result = client.pipeline.crawl(
    CRAWL_URL,
    storage_state=state,
    max_pages=MAX_PAGES,
)

print(f"Pages crawled: {result.pages_crawled}")
print(f"Chunks:        {result.total_chunks}")
print(f"Credits used:  ${result.credits_used:.4f}")
print(f"Remaining:     ${result.credits_remaining:.4f}")
print()

for i, chunk in enumerate(result.chunks[:5], 1):
    print(f"── Chunk {i} ──")
    print(chunk.content[:200])
    print()
'''

_EXAMPLES["12_inspect_vdb.py"] = '''\
"""
12_inspect_vdb.py — Read vector database metadata (always free, no credits charged).

Use this to confirm the dimension and embedding model used during ingestion
before running queries.
"""

import os
from dotenv import load_dotenv
from scrapedatshi import ScrapedatshiClient

load_dotenv()

# ── CONFIGURE ────────────────────────────────────────────────────────────────
VECTOR_DB = "pinecone"                     # ← EDIT: your vector DB key
VECTOR_DB_CONFIG = {                       # ← EDIT: your vector DB config
    "api_key":    os.getenv("PINECONE_API_KEY"),
    "index_host": os.getenv("PINECONE_INDEX_HOST"),
}
# ─────────────────────────────────────────────────────────────────────────────

client = ScrapedatshiClient()

result = client.pipeline.inspect_vectordb(
    vector_db=VECTOR_DB,
    vector_db_config=VECTOR_DB_CONFIG,
)

print(f"Dimension:     {result.dimension}")
print(f"Total vectors: {result.total_vector_count:,}")
print()
print("Suggested embedding models for this dimension:")
for model in result.suggested_models:
    print(f"  • {model.label}")
    print(f"    provider={model.provider}  model={model.model}")
if result.note:
    print()
    print(f"Note: {result.note}")
print()
print("(inspect_vectordb is always free — no credits deducted)")
'''


# ── CLI implementation ────────────────────────────────────────────────────────


def _write_file(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def cmd_init(args: list[str]) -> None:
    project_name = args[0] if args else "scrapedatshi-project"
    target = os.path.abspath(project_name)

    if os.path.exists(target):
        print(f"Error: '{project_name}' already exists.", file=sys.stderr)
        sys.exit(1)

    print(f"\n🚀 Creating scrapedatshi project: {project_name}/\n")

    # Prompt for API key
    api_key = ""
    try:
        api_key = input(
            "Enter your scrapedatshi API key (press Enter to skip): "
        ).strip()
    except (EOFError, KeyboardInterrupt):
        pass

    # Write .env
    env_content = _ENV_TEMPLATE
    if api_key:
        env_content = env_content.replace(
            "SCRAPEDATSHI_API_KEY=sds_...", f"SCRAPEDATSHI_API_KEY={api_key}"
        )
    _write_file(os.path.join(target, ".env"), env_content)

    # Write .gitignore
    _write_file(os.path.join(target, ".gitignore"), _GITIGNORE_TEMPLATE)

    # Write README
    _write_file(os.path.join(target, "README.md"), _README_TEMPLATE)

    # Write example scripts
    examples_dir = os.path.join(target, "examples")
    for filename, content in _EXAMPLES.items():
        _write_file(os.path.join(examples_dir, filename), content)

    # Summary
    files_written = 3 + len(_EXAMPLES)  # .env + .gitignore + README + examples
    print(f"  ✓ .env")
    print(f"  ✓ .gitignore")
    print(f"  ✓ README.md")
    for filename in _EXAMPLES:
        print(f"  ✓ examples/{filename}")

    print(f"\n✅ Project created ({files_written} files)\n")
    print(textwrap.dedent(f"""\
        Next steps:
          1. cd {project_name}
          2. Edit .env — add your API keys
          3. python examples/00_discover_providers.py
          4. python examples/01_chunk_url.py

        Docs: https://scrapedatshi.com/dev
    """))


def main() -> None:
    argv = sys.argv[1:]

    if not argv or argv[0] in ("-h", "--help"):
        print(textwrap.dedent("""\
            scrapedatshi CLI

            Commands:
              init [project-name]   Create a new scrapedatshi sandbox project
                                    (default name: scrapedatshi-project)

            Examples:
              scrapedatshi init
              scrapedatshi init my-rag-project
        """))
        return

    command = argv[0]
    rest = argv[1:]

    if command == "init":
        cmd_init(rest)
    else:
        print(f"Unknown command: {command}", file=sys.stderr)
        print("Run `scrapedatshi --help` for usage.", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
